# Numpy

In [1]:
# imports and packages
import numpy as np

# 1D Array

In [2]:
my_array = [1,2,3]

In [3]:
type(my_array)

list

In [4]:
my_array= np.array([my_array])

In [5]:
np.shape(my_array)

(1, 3)

In [6]:
type(my_array)

numpy.ndarray

In [7]:
my_array = np.array([1,2,3])

In [8]:
np.shape(my_array)

(3,)

# 2D Array

In [10]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])

In [11]:
np.shape(my_array)

(2, 3)

In [12]:
my_array.T
#transposes the array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
np.shape(my_array)

(2, 3)

In [15]:
trans_array = my_array.T

In [16]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
np.shape(trans_array)

(3, 2)

In [18]:
np.sum(trans_array, axis = 0)

array([ 6, 15])

In [19]:
np.sum(trans_array, axis = 1)

array([5, 7, 9])